SSP-59 clicking the save & send button
MohirpoolBatch1/Invoice-Baytul-Coders pull request #20
Opened 2022-08-06 16:28 UTC by bkh77

**Issue #:** [SSP-59](https://mohirpool.atlassian.net/jira/software/c/projects/SSP/boards/5?modal=detail&selectedIssue=SSP-59)

## PR turi

PR'da qanday turdagi o'zgarish bo'lganini belgilang:

- [ ] Bugfix
- [x] Feature
- [ ] Kod stilida o'zgarishlar (formatting, renaming)
- [ ] Refactor(funksional yoki api o'zgarishlari yo'q)
- [ ] Boshqa:

## PR ko'lami

Bu PR quyidagi file'larga yangi kod qo'shgan, yoki o'zgartirish kiritgan:

- Yangi - Component A
- O'zgartirish - Page B
- O'zgaritirish - Component C

## Screenshots

#### oldingi holati:

#### hozirgi holati:

## Avvalgi holatni tasvirlang

- foo

## Hozirgi holatni tasvirlang

- bar

## Bu PR keskin o'zgarishlar keltirib chiqaradimi?

- [ ] Ha (tushuntirish bering):
- [ ] Yo'q

## Boshqa ma'lumotlar

Qo'shimcha ma'lumotlarni shu yerda qoldirishingiz mumkun

## Pull request checklist

PR quyidagilardan qaysi biriga to'g'ri kelsa, belgilab chiqing:

- [ ] Bir necha qavatli prop-drilling ishlatilmayapti
- [ ] Konsolda error va warning'lar tekshirildi, hech qanday error va warning
      yo'q
- [ ] Har bir commit'da jira ticketining kodi belgilangan. Misol ucun
      `feat(SSP-10): mening commit xabarim`
- [ ] Feature branch'ni master branch bilan up-to-date saqlash uchun rebase
      ishlatildi. Boshqacha qilib aytganda, PR raise qilishdan avval rebase
      qilingan

2022-08-07 18:39 UTC, umarmuhandis commented on src/components/FormWindow/index.jsx
> +  })
Shularni hammasini alohida state qilmasdan bitta reducer bilan interaction qilaylik. Sizni holatizda performance'ga ta'sir qiladi, ortiqcha, keraksiz re-render'lar ko'p bo'ladi

2022-08-07 18:44 UTC, umarmuhandis commented on src/components/FormWindow/index.jsx
> +    <div className={`${!isOpenForm && 'hidden'} fixed inset-0 bg-gray-700/40`}>
Shu joyida forma ochilganda ortiqcha "false" degan class qo'shilib qolmaydimi?

2022-08-07 18:46 UTC, umarmuhandis commented on src/index.css
> +<<<<<<< HEAD
Bu nima 👀

2022-08-07 18:49 UTC, umarmuhandis commented on src/components/FormWindow/useForm.js
> +      setState({...state, [e.target.name]: e.target.value})
Agar yangi kelayotgan state, o'zidan oldingi state'ga dependenant bo'lsa `setState`'ga callback funksiya tashlash best practice hisoblanadi: 

`setState(prevState => ({...prevState, [e.target.name]: e.target.value}))`

2022-08-07 18:52 UTC, umarmuhandis commented on src/components/FormWindow/index.jsx
> +  }
Bu ikkalasini useCallback'ga o'rash kerak

2022-08-07 18:58 UTC, umarmuhandis commented on src/pages/Homepage/Homepage.jsx
>    )
Shu state'ni olib tashlang, kerakmas ortiqcha narsa. O'rniga oddiygina const bilan yozib qo'ying: 

```
const amountInvoices = items.length ? `There are ${items.length} total invoices` : 'No invoices',
```

2022-08-07 19:00 UTC, umarmuhandis commented on src/components/FormItemRow/util.js
> +export function totalAmount(price, quantity) {
Shuni nomini o'zgartirish kerak. Bu narsa funksiya, qandaydur action bajaryabti, shuning uchun nomini ham shunga moslash kerak. Reference: https://github.com/kettanaito/naming-cheatsheet#naming-functions

2022-08-07 19:03 UTC, umarmuhandis requested changes
Commentlar qoldirdim, to'g'irlab qaytadan request qiling

2022-08-09 05:49 UTC, bkh77 commented on src/components/FormWindow/index.jsx
> +    <div className={`${!isOpenForm && 'hidden'} fixed inset-0 bg-gray-700/40`}>
ok

2022-08-09 06:14 UTC, bkh77 commented on src/components/FormWindow/useForm.js
> +      setState({...state, [e.target.name]: e.target.value})
ok

2022-08-09 06:15 UTC, bkh77 commented on src/pages/Homepage/Homepage.jsx
>    )
ok

2022-08-09 08:19 UTC, bkh77 commented on src/components/FormItemRow/util.js
> +export function totalAmount(price, quantity) {
ok

2022-08-09 12:24 UTC, bkh77 commented on src/components/FormWindow/index.jsx
> +  }
ok

2022-08-11 14:34 UTC, bkh77 commented on src/components/FormWindow/index.jsx
> +  })
bularni hammasini redux toolkitga utkazdim

2022-08-12 17:58 UTC, umarmuhandis commented on src/app/itemSlice.js
> +    getImputValues: (state, action) => {
`getInputValues` ?

2022-08-13 06:40 UTC, bkh77 commented on src/app/itemSlice.js
> +    getImputValues: (state, action) => {
ok

2022-08-15 09:14 UTC, umarmuhandis approved these changes

2022-08-19 05:08 UTC, khumoyun-eddie approved these changes

2022-08-19 05:12 UTC, merged